#pragma once
enum tnumber { TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, 
	TPLUS, TMINUS, TMUL, TDIV, TMOD, TASSIGN,
	TEQUAL, TNOTEQU, TLESSE, TGREATE, TAND, TOR, TINC, TDEC, 
	TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TIDENT, 
	TLPAREN, TRPAREN, TLBRACE, TRBRACE, TLSQUARE, TRSQUARE, TCOMMA, TDOT, TSEMI,
	TNOT, TLESS, TGREAT, TINTNUM, TFLOATNUM, TSTRING, TCHAR, TFLOAT, TERROR};
