enum tnumber {
    TEOF,
    TCONST, TELSE, TIF, TINT, TFLOAT, TCHAR, TRETURN, TVOID, TWHILE,
    TPLUS, TMINUS, TMUL, TDIV, TMOD,
    TASSIGN, TEQUAL, TNOTEQU, TLESS, TGREAT, TLESSE, TGREATE,
    TNOT, TAND, TOR, TINC, TDEC,
    TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN,
    TIDENT, TINTNUM, TFLOATNUM, TSTRING,
    TDOT, TCOMMA, TSEMI, TLPAREN, TRPAREN, TLSQUARE, TRSQUARE, TLBRACE, TRBRACE,
    TERROR
};